applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  imageEos:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: eosio-testnet.image.repository
            after: eosio-testnet.image.tag
            
  eosio-testnet.replicaCount: 
    title: nodeos count
    type: integer
    default: 4
    description: Number of nodeos
        
  eosio-testnet.producerCount: 
    title: producer count
    type: integer
    default: 4
    description: Number of producers, should not be greater than the number of nodeos.
      
  eosio-testnet.genesis.initial_timestamp: 
    title: genesis timestamp
    type: string
    default: "2018-09-12T16:21:19.132"
    title: Initial genesis timestamp
    
  eosio-testnet.genesis.signatureProvider: 
    title: geneesis key pair
    type: string
    default: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEY:5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3
    description: genesis public/private key pair
    
  eosio-testnet.service.loadBalancerSourceRanges:
    title: Source IP ranges
    type: string
    default: 0.0.0.0/0
    description: a list of CIDRs seperated by commas.
    pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(3[0-2]|[1-2][0-9]|[0-9]))(,(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(3[0-2]|[1-2][0-9]|[0-9])))*$
    
  eosio-testnet.producerKeys:
    title: Private keys of producers
    type: string
    description: a list of private keys seperated by commas.
    
required:
- name
- namespace
- imageEos
- eosio-testnet.replicaCount
- eosio-testnet.producerCount
- eosio-testnet.genesis.signatureProvider
- eosio-testnet.genesis.initial_timestamp
